Enable sdcmonitor
dell/csm-operator pull request #123
Opened 2022-11-01 19:21 UTC by kumarkgosa

# Description
Adding support to sdc-monitor for powerflex driver through operator.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2022-11-01 19:24 UTC, bharathsreekanth commented
Update with GitHub issue #.This is part of CSM operator feature, so you can include that.

2022-11-01 19:24 UTC, bharathsreekanth commented
Also, can you add some way for others to know that the SDC monitor side-car was deployed in the PR?

2022-11-01 19:53 UTC, JacobGros commented
can we add unit tests for the new code added?

2022-11-01 20:14 UTC, jooseppi-luna requested changes
We should try to get coverage back up to ~95%, which is where it was before this PR. I can work with you on this, hmu

2022-11-01 20:25 UTC, kumarkgosa commented on pkg/drivers/powerflex.go
> +func Getmdmipforsdc(sidenv []corev1.EnvVar, mdmFin string) (corev1.EnvVar, error) {
Changed it to GetMDMIpForSdc jooseppi.. Thank you

2022-11-01 20:34 UTC, JacobGros commented
Are we able to disable the sdc-monitor car?
I see in samples, 
https://github.com/dell/csm-operator/blob/8fe5a4c8bd2933bcf3d44ee0b133f01b74b595e4/samples/storage_csm_powerflex_v240.yaml#L41 

but in screenshot its enabled

2022-11-01 20:36 UTC, JacobGros commented
2.3 and 2.4 should both support enable/disable sdc-monitor
can we add the enable/disable flag to this section: https://github.com/dell/csm-operator/blob/8bb767883348cbfe4de48c79abcab74dc74dc069/samples/storage_csm_powerflex_v230.yaml#L38 as well?

2022-11-01 20:52 UTC, kumarkgosa commented
> Are we able to disable the sdc-monitor car? I see in samples,
> 
> https://github.com/dell/csm-operator/blob/8fe5a4c8bd2933bcf3d44ee0b133f01b74b595e4/samples/storage_csm_powerflex_v240.yaml#L41
> 
> but in screenshot its enabled

Yes, we can disable/enable it manually. By default it will be disabled.

2022-11-07 18:57 UTC, jooseppi-luna approved these changes
lgtm nice work!

2022-11-07 20:26 UTC, abhi16394 commented on samples/storage_csm_powerflex_v230.yaml
>      # comment the following section if you don't want to run the monitoring sidecar
could you remove this comment and add comment similar to storage_csm_powerflex_v240.yaml

2022-11-07 20:59 UTC, abhi16394 approved these changes
lgtm

2022-11-07 21:01 UTC, jooseppi-luna approved these changes

2022-11-07 21:03 UTC, merged