Update support for Observability module 1.6
dell/csm-operator pull request #173
Opened 2023-02-22 03:13 UTC by P-Cao

# Description
Update observability manifest files and PowerFlex and PowerScale 2.6 sample files.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/583|

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2023-02-22 03:44 UTC, taohe1012 submitted a review, later dismissed

2023-02-22 03:53 UTC, baoy1 approved these changes

2023-02-22 06:20 UTC, rensyct requested changes
@P-Cao , Please remove 1.2 related manifests and samples as in Operator we support only n-2 versions of modules and drivers

2023-02-22 06:27 UTC, P-Cao commented
> @P-Cao , Please remove 1.2 related manifests and samples as in Operator we support only n-2 versions of modules and drivers

Done. And v240 samples use v1.3.0 config version.

2023-02-22 08:00 UTC, baoy1 approved these changes

2023-02-22 08:09 UTC, rensyct approved these changes

2023-02-23 01:47 UTC, taohe1012 approved these changes

2023-02-23 01:48 UTC, baoy1 approved these changes

2023-02-23 04:58 UTC, rensyct approved these changes

2023-02-23 04:58 UTC, merged