add the changes to support mke 3.5.x for latest vxflexos.
dell/csm-operator pull request #180
Opened 2023-03-03 13:59 UTC by VamsiSiddu-7

# Description
This pr adds the changes to support mke 3.5.x for latest vxflexos driver.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/583 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Successfully Installed the csi-powerflex driver using csm-operator on mke 3..5.4 cluster 
- [x] Ran Cert-csi  and it passed with 100%
 
![cert-csi-operator](https://user-images.githubusercontent.com/103578883/222738683-ff812dd5-5775-4f5d-ab24-4c3c6815e179.PNG)

2023-03-03 16:29 UTC, rensyct requested changes

2023-03-03 16:29 UTC, rensyct commented on README.md
> +    * Upstream Kubernetes cluster v1.21, v1.24, v1.25, v1.26
We dont have to call out the support for K8s v1.21. So please revert the change in this file

2023-03-06 05:30 UTC, rensyct approved these changes

2023-03-06 05:39 UTC, ashleyvjoy approved these changes

2023-03-06 05:46 UTC, merged