Feature StorageCapacityTracking for Powermax
dell/csm-operator pull request #281
Opened 2023-06-26 09:58 UTC by tssushma

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
![image](https://github.com/dell/csm-operator/assets/98810659/98e5af5d-2377-42aa-9a4f-d8f0484d2563)

- [ ] Test A
- [ ] Test B

2023-06-30 11:44 UTC, tssushma commented on pkg/drivers/powermax.go
> +	CSIStorageCapacityEnabled = "false"
This parameter is a redundant entry.
Rectified it and removed this from constant list.

2023-07-03 05:46 UTC, delldubey approved these changes
lgtm

2023-07-04 11:25 UTC, suryagupta4 commented
We can also give users an option for configuring the `capacity-poll-interval`
This is done for PowerStore & PowerScale, refer here:
https://github.com/dell/csm-operator/blob/main/samples/storage_csm_powerstore_v270.yaml#L65
https://github.com/dell/csm-operator/blob/main/samples/storage_csm_powerscale_v270.yaml#L249

2023-07-06 07:43 UTC, rensyct commented
@tssushma , is this change intended for 2.7 or 2.8 version of the driver

2023-07-07 09:30 UTC, tssushma commented
> @tssushma , is this change intended for 2.7 or 2.8 version of the driver



> @tssushma , is this change intended for 2.7 or 2.8 version of the driver

@rensyct , Done updating the version to v2.8.
@suryagupta4, Done adding capacity-poll-interval configuration variable for giving the users an option for configuring poll interval.

2023-07-07 13:05 UTC, rensyct requested changes

2023-07-07 13:05 UTC, rensyct commented on operatorconfig/driverconfig/powermax/v2.8.0/upgrade-path.yaml
> +minUpgradePath: v2.6.0
Should be 2.7.0

2023-07-07 13:05 UTC, rensyct commented on samples/storage_csm_powermax_v280.yaml
> +      image: dellemc/csi-powermax:v2.7.0
should be v2.8.0

2023-07-07 13:05 UTC, rensyct commented on tests/config/driverconfig/powermax/v2.7.0/upgrade-path.yaml
> -minUpgradePath: v2.6.0
Please remove test files related to v2.7.0

2023-07-07 13:05 UTC, rensyct commented on tests/config/driverconfig/powermax/v2.8.0/upgrade-path.yaml
> +minUpgradePath: v2.6.0
Should be v2.7.0

2023-07-07 13:05 UTC, rensyct commented on operatorconfig/driverconfig/powermax/v2.8.0/controller.yaml
> +          image: dellemc/csi-powermax:v2.7.0
should be v2.8.0

2023-07-07 13:05 UTC, rensyct commented on operatorconfig/driverconfig/powermax/v2.8.0/node.yaml
> +          image: dellemc/csi-powermax:v2.7.0
Should be v2.8.0

2023-07-07 13:05 UTC, rensyct commented on samples/storage_csm_powermax_v280.yaml
> +    # Config version for CSI PowerMax v2.7.0 driver
Should be v2.8.0

2023-07-07 13:05 UTC, rensyct commented on samples/storage_csm_powermax_v280.yaml
> +      # Image for CSI PowerMax driver v2.7.0
Should be v2.8.0

2023-07-07 13:05 UTC, rensyct commented on tests/config/driverconfig/powermax/v2.8.0/node.yaml
> +          image: dellemc/csi-powermax:v2.7.0
Should be v2.8.0

2023-07-10 12:05 UTC, shanmydell approved these changes

2023-07-10 12:05 UTC, merged