Adds obsv samples for CSI Powermax
dell/csm-operator pull request #299
Opened 2023-07-25 13:19 UTC by delldubey

# Description
- Add Observability for CSI Powermax
- Add unit tests for powermax related changes in observability.
- 
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/908|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
- [x] Unit Tests
- [x] Cluster Tests

2023-08-04 20:54 UTC, jooseppi-luna requested changes
Need some e2e tests for PowerMax + Observability -- write similar tests to what we have for PowerFlex + Obs and PowerScale + Obs
Add cert-manager to yamls as per this PR: https://github.com/dell/csm-operator/pull/310

If you need any help or want to talk through any of this, hmu on slack

2023-08-22 08:24 UTC, shanmydell approved these changes

2023-08-29 14:59 UTC, delldubey commented
> Need some e2e tests for PowerMax + Observability -- write similar tests to what we have for PowerFlex + Obs and PowerScale + Obs Add cert-manager to yamls as per this PR: #310
> 
> If you need any help or want to talk through any of this, hmu on slack

Added.

2023-08-29 16:43 UTC, shanmydell approved these changes

2023-08-30 05:20 UTC, boyamurthy approved these changes
LGTM.

2023-08-30 21:01 UTC, jooseppi-luna requested changes

2023-08-30 21:02 UTC, jooseppi-luna commented
Other than my one comment everything looks good, if you can address it by 6:00 AM EST/3:30 PM IST I can approve

2023-08-31 07:15 UTC, boyamurthy submitted a review, later dismissed
LGTM.

2023-08-31 08:43 UTC, boyamurthy approved these changes
LGTM.

2023-08-31 09:23 UTC, jooseppi-luna approved these changes

2023-08-31 09:41 UTC, merged

2023-08-31 15:07 UTC, santhoshatdell commented
It looks _operatorconfig/moduleconfig/common/version-values.yaml_ is not updated for PowerMax + Obs.
Shouldn't we also need karavi-metrics-powermax.yaml file for Obs 1.6.0 ?

+CC  @donatwork 

![image](https://github.com/dell/csm-operator/assets/111809751/1fe57af1-c825-4ccf-8986-c9c575b60334)

2023-08-31 15:48 UTC, donatwork reviewed
The versions need updating.

2023-08-31 15:48 UTC, donatwork commented on samples/storage_csm_powermax_v280.yaml
> +      configVersion: v1.5.0
Should be v1.6.0.

2023-08-31 15:48 UTC, donatwork commented on samples/storage_csm_powermax_v280.yaml
> +          image: dellemc/csm-metrics-powermax:v1.1.0
Should be v1.2.0.

2023-08-31 15:48 UTC, donatwork commented on samples/storage_csm_powermax_v280.yaml
> +          image: dellemc/csm-topology:v1.5.0
Shoudl be v1.6.0.