Update csi-unity 2.8.0 driver support to CSM Operator
dell/csm-operator pull request #300
Opened 2023-07-26 10:19 UTC by karthikk92

# Description
Update csi-unity 2.8.0 driver support to CSM Operator

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/885 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

2023-07-27 08:18 UTC, rensyct requested changes
@karthikk92, please check and correct the version for Unity driver in all places wherever applicable

2023-07-27 08:18 UTC, rensyct commented on operatorconfig/driverconfig/unity/v2.8.0/controller.yaml
> +          image: dellemc/csi-unity:v2.7.0
Should this not be 2.8.0?

2023-07-27 09:18 UTC, karthikk92 commented on operatorconfig/driverconfig/unity/v2.8.0/node.yaml
> +          image: dellemc/csi-unity:v2.7.0
This is the test file , since we don't have 2.8.0 build released , from 2.6.0 to 2.7.0 updated.

2023-07-27 09:25 UTC, karthikk92 commented on operatorconfig/driverconfig/unity/v2.8.0/controller.yaml
> +          image: dellemc/csi-unity:v2.7.0
Updated

2023-07-27 09:43 UTC, karthikk92 commented
> @karthikk92, please check and correct the version for Unity driver in all places wherever applicable

taken care

2023-07-31 07:02 UTC, panigs7 approved these changes

2023-07-31 07:16 UTC, rensyct commented
@karthikk92 , please sign all your commits

2023-07-31 09:42 UTC, karthikk92 commented
> @karthikk92 , please sign all your commits

Take care

2023-07-31 09:58 UTC, rensyct approved these changes

2023-07-31 09:58 UTC, merged