Remove resiliency duplicated extra args in sample yaml files
dell/csm-operator pull request #302
Opened 2023-07-28 14:29 UTC by xuluna

# Description
Remove the duplicated `arrayConnectivityPollRate` args in CR yaml files.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/898 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Deployed the driver with resiliency enabled in e2e test on a local Kubernetes setup. Modified the resiliency image to use different versions/tags and repos to verify that users can specify a different resiliency image.

2023-07-28 15:03 UTC, shaynafinocchiaro approved these changes

2023-07-31 04:22 UTC, chimanjain approved these changes

2023-07-31 04:50 UTC, suryagupta4 approved these changes

2023-07-31 10:06 UTC, rensyct requested changes
Please remove the duplicate entry from the samples under _tests/e2e/testfiles_ folder and also from _pkg/modules/testdata/cr_powerstore_resiliency.yaml_ file

Should we not remove the duplicate args from _samples/storage_csm_powerflex_v270.yaml_?

2023-07-31 17:34 UTC, rensyct approved these changes

2023-07-31 17:34 UTC, rensyct commented
> > Please remove the duplicate entry from the samples under _tests/e2e/testfiles_ folder and also from _pkg/modules/testdata/cr_powerstore_resiliency.yaml_ file
> > Should we not remove the duplicate args from _samples/storage_csm_powerflex_v270.yaml_?
> 
> I don't see a duplicate podmon args in storage_csm_powerflex_v270.yaml and cr_powerstore_resiliency.yaml files? This duplicates were created from my last PR #296 where a customer requested extra args in sample files. No change was made to tests/e2e/testfiles folder.

I see that one is defined under controller and the other one under node.

2023-07-31 17:46 UTC, merged