Storage Capacity Tracking for CSI-Powerflex
dell/csm-operator pull request #323
Opened 2023-08-18 11:23 UTC by ashleyvjoy

# Description
This PR adds addresses changes in csm-operator to support Storage Capacity Tracking feature for PowerFlex driver

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| (https://github.com/dell/csm/issues/876) |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Deployed driver using csm-operator with sct flag set to true and described csi-driver. StorageCapacity is enabled and csistoraagecapacitiesobjects are created. Successfully executed Cert-CSI test suites and StorageCapacity Functional test suites. Test Suites passed 100%
- [x] Deployed driver using csm-operator with sct flag set to false and described csi-driver. StorageCapacity is not enabled
<img width="379" alt="sctoperatorenabled" src="https://github.com/dell/csm-operator/assets/110008193/87d386d5-bde2-46d4-9031-b2dd318e2d2d">
<img width="496" alt="Screenshot 2023-08-17 231102" src="https://github.com/dell/csm-operator/assets/110008193/2bd62670-948c-4e96-a621-f31436abd003">

```
INFO 1. ScalingSuite {replicas: 2, volumes: 5, volumeSize: 8Gi}
INFO 2. CloneVolumeSuite {pods: 2, volumes: 1, volumeSize: 8Gi}
INFO 3. VolumeIoSuite {volumes: 2, volumeSize: 8Gi chains: 2-2}
INFO 4. SnapSuite {snapshots: 3, volumeSize; 8Gi}
INFO 5. ReplicationSuite {pods: 2, volumes: 5, volumeSize: 8Gi}
Does it look OK? (Y)es/(n)o
-> y
INFO Avg time of a run:   60.37s
INFO Avg time of a del:   13.81s
INFO Avg time of all:     79.24s
INFO During this run 100.0% of suites succeeded
------------------------------------------------------------
./cert-csi functional-test capacity-tracking --sc vxflexos-xfs --drns vxflexos --pi 5m
INFO Starting cert-csi; ver. 0.8.1
INFO Using EVENT observer type
INFO Using default config
INFO Successfully loaded config. Host: https://
INFO Created new KubeClient
INFO Found 1 topology segment(s) in csinode
INFO Creating capacity-tracking-4367b929 storage class
INFO Waiting for CSIStorageCapacity to be CREATED for capacity-tracking-4367b929 storage class in vxflexos namespace
INFO All CSIStorageCapacity are created in 2.005263936s
INFO Deleting capacity-tracking-4367b929 storage class,
INFO Waiting for CSIStorageCapacity to be DELETED for capacity-tracking-4367b929 storage class in vxflexos namespace
INFO All CSIStorageCapacity are deleted in 2.005498431s
INFO Updating CSIStorageCapacity for vxflexos-xfs storage class, setting capacity to 0
INFO Creating capacity-tracking-pod-d0a8eb93 pod using vxflexos-xfs storage class
INFO capacity-tracking-pod-d0a8eb93 pod is PENDING
INFO Waiting for provisioner to POLL GetCapacity for vxflexos-xfs storage class in 5m0s
INFO Provisioner POLLED GetCapacity for vxflexos-xfs storage class
INFO Waiting for pod capacity-tracking-pod-d0a8eb93 to be READY
INFO capacity-tracking-pod-d0a8eb93 pod is RUNNING
INFO SUCCESS: CapacityTrackingSuite in 1m10.092508801s
INFO Trying to connect to cluster...
INFO Created new KubeClient
INFO During this run 100.0% of suites succeeded
```

2023-08-21 06:19 UTC, khareRajshree requested changes
Please update the e2e files and execute the e2e tests with the latest changes done for SCT.

2023-08-21 09:16 UTC, khareRajshree commented on pkg/modules/replication.go
> +	XCSIReplicaPrefix = "X_CSI_REPLICATION_PREFIX" //
please remove the comment characters.

2023-08-22 05:03 UTC, ashleyvjoy commented
> Please update the e2e files and execute the e2e tests with the latest changes done for SCT.

Executed the e2e test and logs are attached in Jira.

2023-08-22 05:03 UTC, ashleyvjoy commented on pkg/modules/replication.go
> +	XCSIReplicaPrefix = "X_CSI_REPLICATION_PREFIX" //
> please remove the comment characters.

Done

2023-08-22 05:06 UTC, khareRajshree approved these changes

2023-08-22 05:20 UTC, rensyct submitted a review, later dismissed

2023-08-22 05:20 UTC, rensyct commented on api/v1/types.go
> +	ReverseProxyServer ModuleType = "csipowermax-reverseproxy" // #nosec G101
should this change be reverted

2023-08-22 05:23 UTC, ashleyvjoy commented on api/v1/types.go
> +	ReverseProxyServer ModuleType = "csipowermax-reverseproxy" // #nosec G101
Yes. Removed that

2023-08-22 05:25 UTC, khareRajshree submitted a review, later dismissed

2023-08-22 05:36 UTC, rensyct approved these changes

2023-08-22 05:43 UTC, panigs7 approved these changes

2023-08-22 06:16 UTC, merged