Adding volume prefix for Unity
dell/csm-operator pull request #379
Opened 2023-10-23 14:24 UTC by adamginna-dell

Added volume name prefix for Unity driver .

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/989|

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Executed cert-csi tests .

2023-10-23 14:57 UTC, mbasha-dell approved these changes

2023-10-23 15:08 UTC, jooseppi-luna requested changes
could you add this to the e2e sample files for unity as well? thanks!

2023-10-25 13:21 UTC, jooseppi-luna approved these changes
lgtm, thanks!

2023-10-25 13:47 UTC, mbasha-dell approved these changes

2023-10-25 18:36 UTC, merged