update golangci-lint
dell/csm-operator pull request #456
Opened 2024-02-08 11:12 UTC by cbartoszDell

2024-02-08 12:46 UTC, shaynafinocchiaro approved these changes

2024-02-08 15:24 UTC, cbartoszDell commented on .github/workflows/linters.yaml
> +          version: v1.55
```suggestion
          version: latest
```

2024-02-13 16:28 UTC, donatwork requested changes
All of the linter errors were previously fixed. Please fix linter errors since you touched the code last.

2024-02-13 16:28 UTC, KerryKovacevic submitted a review, later dismissed

2024-02-15 11:44 UTC, cbartoszDell commented
This PR is only for upgrading the versions on Go and golangci-lint action. This is required to make sure that golangci-lint is always the latest version and is working with the latest version of Go. This requests is being made to all CSM drivers and modules to make sure linter action keeps working. Fixing linter warnings is not a part of scope of this upgrade PR.

Also, @donatwork FYI since I opened this PR 5 other PRs got merged with `linters` action failing.

2024-02-15 13:27 UTC, donatwork approved these changes
OK, I'll approve. We should start enforcing the linter check at some point.

2024-02-22 17:40 UTC, jooseppi-luna approved these changes

2024-02-22 17:43 UTC, shefali-malhotra approved these changes
LGTM

2024-02-22 17:44 UTC, nitesh3108 approved these changes

2024-02-22 17:44 UTC, merged