Verified merge fixed release v1.4.2 (#479)
dell/csm-operator pull request #480
Opened 2024-02-19 16:30 UTC by JacobGros

* Add permissions for SC removal. (#431)

* Bump_up_csm-operator_version_to_1.4.1 (#434)

* Patch version support (#433)

* Adding support of v2.9.1 for Pmax, Pscale, PFlex and unity

* Updating module config version for Pmax, Pscale, PFlex and unity

* Update storage_csm_powerflex.yaml

* version changed to 2.9.1

* version changed to 2.9.1

* Enabling github actions for all branch

* updated version to 2.9.1 for unity, powerflex, powerscale and powermax

* Adding the support of PStore v2.9.1

* Adding the support of PFlex v2.9.1

* Version bumpup replication 1.7.1

* Bump up version for authorization, resiliency

* update csi-metadata-retriever version to 1.6.1

* update reverseproxy version to 2.8.1

---------

* Change namespace name to match documentation. (#437)

* go-yaml version update (#438)

* go-yaml version update

* update go-yaml package to latest

* remove extra verbs

* remove duplicate verbs and add correct test files for resiliency UT

---------

* [bug-1120]: Update Authorization sidecar to use insecure flag (#442)

* fix auth cert

* remove constant

* remove duplicate verbs

* reverting #426 changes (#444)

* Update final manifests for posting of Operator 1.4.1 (#445)

* KRV-20573/csm status (#446)

* add module status

* Adding CSM Module status

* Addressing the comments for PR

* Making code reusable

* Fix formatting issue

* Resolving gosec issue

* Final manifest update and apex client (#447)

* Add csm watch permissions. (#448)

* Merged CSM Module Status

* Fix App-Mob node error (#457)

* Bump up CSM Operator version to 1.4.2 (#458)

* update csm operator version to 1.4.2

* bump-up-op-version-1.4.2

* updated version in operator.yaml

* adding missing arg to fix e2e

* update authorization e2e (#459)

* skip cert validation in e2e (#460)

* Fixing FSGroupPolicy issue (#463)

* Fixing FSGroupPolicy issue

* Add unit test

---------

* Fix for controller race, daemon status, and obs namespace  (#464)

* test controller state calc

* add debug logs

* check for driver

* add daemonnset update

* adds ns fix for when pod ns dis not csm ns

* add ns check for daemon and deployment as well

* fix typo

* fix typo

* explicitly return nil

* add missing replace statements

---------

* Auth proxy status fix (#465)

* actions

* working on auth proxy status check

* finished status check

* fix 1

* fix or

* code compiles

* keep auth proxy out of daemonset check

* trying to figure out deployment name

* formatting

* fix auth name in if condition

* no daemonset

* fix

* added log statements

* added another log statement

* fix log statement

* logs logs logs

* compile

* more logs

* add logs and try updating status from handlesuccess

* remove UpdateStatus call for now

* adding csm label to auth

* remove extraneous string replacement

* removing commented code

* Update actions.yml

* fix merge issue

* fix fmt

* fix pscale + obs issue  (#467)

* fix some issues

* fiix label issue, add debug logs

* add more debug

* more  debugg lines

* fix pscale issue

* remmove debug logs

* gofmt

* set available to 0 en deployment is not checked

* fix if check

---------

* update final manifests (#468)

* fix vetting issues (#477)

---------

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-02-19 22:19 UTC, jooseppi-luna commented
Just as an update, ran all PFlex E2E tests and only failed on one of the last app mobility scenarios because a docker image pull of an artifactory image was acting up (not operator related at all). Did find a weird edge case with PowerScale where the controller failed due to the csi-metadata-retriver v1.7.0 image not existing yet, but the csm status was marked as successful. I don't think this is a regression being introduced in this PR, so I will approve the PR.

```
[root@master-1-Zaglt7mQUY8Wg observability]# kubectl get pods -n isilon
NAME                                 READY   STATUS    RESTARTS       AGE
isilon-controller-67c5c64b86-bptxg   1/6     Error     12 (14s ago)   2m52s
isilon-node-2h9bt                    2/2     Running   0              2m52s
isilon-node-mtdmd                    2/2     Running   0              2m52s
[root@master-1-Zaglt7mQUY8Wg observability]# kubectl get csm -A
NAMESPACE   NAME     CREATIONTIME   CSIDRIVERTYPE   CONFIGVERSION   STATE
isilon      isilon   2m55s          isilon          v2.10.0         Succeeded
[root@master-1-Zaglt7mQUY8Wg observability]#
```

2024-02-19 22:19 UTC, jooseppi-luna approved these changes

2024-02-20 13:52 UTC, jooseppi-luna requested changes
can we run gofumpt on csm_controller.go and status.go?

2024-02-20 13:52 UTC, jooseppi-luna commented on controllers/csm_controller.go
> +	CSMVersion = "v1.9.2"
Should probably be 1.10.0?

2024-02-20 13:52 UTC, jooseppi-luna commented on bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
> +  version: 1.4.2
why is this 1.4.2?

2024-02-20 13:52 UTC, jooseppi-luna commented on bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
> +  - image: docker.io/dellemc/dell-csm-operator:v1.4.2
why is this 1.4.2?

2024-02-20 13:52 UTC, jooseppi-luna commented on controllers/csm_controller.go
> +	//if this pod is an obs. pod, namespace might not match csm namespace
add space at beginning of comment

2024-02-20 13:52 UTC, jooseppi-luna commented on pkg/utils/status.go
> +	var err error = nil
drop ` = nil` part

2024-02-20 13:52 UTC, jooseppi-luna commented on pkg/utils/status.go
> +			log.Info("HandleSuccess Driver stat changed to Succeeded")
*state

2024-02-20 16:38 UTC, JacobGros commented
Closing and re-opening due to verified issue

2024-02-20 16:38 UTC, closed without merging