Finial Manifest update
dell/csm-operator pull request #521
Opened 2024-03-11 08:55 UTC by HarishH-DELL

# Description
Finial Manifest update

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1091 |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

2024-03-11 09:43 UTC, rajendraindukuri commented on bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
> -  relatedImages:
@HarishH-DELL This section should be there. Please add it manually if deleted during building manifests

2024-03-11 10:26 UTC, panigs7 requested changes

2024-03-11 10:26 UTC, panigs7 commented on bundle/manifests/connectivity-client-docker-k8s-cert_v1_secret.yaml
> +type: Opaque
Revert this file. We don't require this file while bundling.

2024-03-11 10:26 UTC, panigs7 commented on bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
> +    operators.operatorframework.io/builder: operator-sdk-v1.34.1
Are you using operator-sdk version 1.34.1?

2024-03-11 10:26 UTC, panigs7 commented on bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
>    skips:
Revert this relateImages deletion.

2024-03-11 10:26 UTC, panigs7 commented on bundle/metadata/annotations.yaml
> -  com.redhat.openshift.versions: v4.13-v4.14
Remove the changes in the annotations.yaml file. Only change to be preserved is the sdk version used to generate the files.

2024-03-11 10:26 UTC, panigs7 commented on deploy/operator.yaml
>        - args:
Revert all the changes in this file

2024-03-11 13:30 UTC, panigs7 approved these changes

2024-03-12 04:43 UTC, rajendraindukuri approved these changes

2024-03-12 04:45 UTC, merged