Minimal manifests poc
dell/csm-operator pull request #679
Opened 2024-09-04 08:12 UTC by meggm

# Description
Need for a simple and minimal manifest file using existing Operator CRD.
Changes include adding the below default values in the code:

- reverse proxy module for PowerMax driver
- disable sdc-monitor and health-monitor by default 
- added the default check for kubelet config directory 
- fixed issues with initContainer and MDM key not found issue in PowerFlex driver

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1449 |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-09-09 23:57 UTC, tdawe approved these changes
LGTM

2024-09-10 04:39 UTC, mgandharva submitted a review, later dismissed

2024-09-10 05:08 UTC, harishp8889 approved these changes

2024-09-10 05:46 UTC, bandak2 submitted a review, later dismissed

2024-09-10 05:56 UTC, HarishH-DELL approved these changes

2024-09-10 06:24 UTC, nitesh3108 commented on operatorconfig/driverconfig/powermax/v2.12.0/controller.yaml
Is this intentional creating 2.12.0 structure only for powermax and not for other drivers.

2024-09-10 06:43 UTC, harishp8889 commented on operatorconfig/driverconfig/powermax/v2.12.0/controller.yaml
@nitesh3108 for powermax alone there are some driver changes and we need to use nightly image for now until the new version is released and hence I have created the latest version for powermax alone and used nightly image in that. Also there are additional params added in the yamls which are only supported in the latest driver

2024-09-10 07:08 UTC, harishp8889 requested changes

2024-09-10 07:08 UTC, harishp8889 commented on samples/storage_csm_powerstore_v2110.yaml
> +      image: "dellemc/csi-powerstore:nightly"
@gilltaran why this is nightly image? Please change it to `v2.11.0`

2024-09-10 07:30 UTC, closed without merging