Minimal CR for resiliency
dell/csm-operator pull request #691
Opened 2024-09-16 07:28 UTC by adarsh-dell

# Description
Added support for the `resiliency `module in the minimal CR for the `PowerStore `driver. This allows users to simply enable or disable the module, with only an enables field under each module’s spec—no components, arguments, or environment variables are needed. Since no changes were required in the core logic and the code was already designed to handle this case, the only requirement was to add default values that will be prepopulated and can be overwritten by the values from the CR.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1449|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Deployed the CSM 1.11.0 drivers (v2.11.0 CSI-PowerStore) and ensured that the driver starts up properly this test backward compatibility.
- [x] Updated the value in the old CR (v2.11.0) to verify that the default value is being overwritten, giving preference to the CR value over the prepopulated module config.
- [x] Installed the driver with the minimal configuration of the resiliency module and conducted basic sanity testing. This included taking down the interface where the pod was scheduled, monitored by podmon, and checking the logs to ensure the connectivity status is false. Taints were added to the node, the pod was rescheduled to another node, and once the node’s interface came back up, the taints were removed and the same connectivity status was reflected in the logs.

![image (40)](https://github.com/user-attachments/assets/b786e6f8-dc32-411f-91f1-e95f69e9d745)

![image (39)](https://github.com/user-attachments/assets/77ca2313-ec1e-4318-933a-455483cf4a68)

![image (38)](https://github.com/user-attachments/assets/37400ed1-6674-4709-a598-e246925800a7)

![image (37)](https://github.com/user-attachments/assets/2ff69bb4-22cb-4d22-aa3f-c08969371e7c)

2024-09-16 08:31 UTC, adarsh-dell commented
E2E is being covered under https://github.com/dell/csm-operator/pull/690/files.
Thanks

2024-09-16 08:37 UTC, suryagupta4 submitted a review, later dismissed

2024-09-16 08:49 UTC, meggm approved these changes

2024-09-16 09:20 UTC, AkshaySainiDell requested changes

2024-09-16 09:20 UTC, AkshaySainiDell commented on operatorconfig/moduleconfig/resiliency/v1.11.0/container-powerstore-controller.yaml
> +  # Below 4 args should not be modified.
This comment is not required in the operatorconfig.

2024-09-16 09:20 UTC, AkshaySainiDell commented on operatorconfig/moduleconfig/resiliency/v1.11.0/container-powerstore-node.yaml
> +  # Below 4 args should not be modified.
Same as above, this comment is not required in the operatorconfig.

2024-09-16 09:20 UTC, AkshaySainiDell commented on operatorconfig/moduleconfig/resiliency/v1.11.0/container-powerstore-node.yaml
> +  # Default value: 8083
These comment are not required in the operatorconfig.

2024-09-16 09:20 UTC, AkshaySainiDell commented on pkg/modules/resiliency.go
> +	NodeMode       = "node"
It seems these constants are utilized within this package. Please check if we can make them private.

2024-09-16 10:00 UTC, AkshaySainiDell approved these changes

2024-09-16 12:32 UTC, ashleyvjoy approved these changes

2024-09-16 13:21 UTC, suryagupta4 approved these changes

2024-09-17 04:17 UTC, chimanjain approved these changes

2024-09-17 04:20 UTC, merged