E2E for CSI-PowerMax driver with minimal CR
dell/csm-operator pull request #749
Opened 2024-10-17 10:23 UTC by suryagupta4

# Description

This PR includes:

- e2e changes for CSI-PowerMax minimal sample (sample that has least fields).
- Image field is added in minimal test sample yamls since we have to use nightly tagged images for e2e.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1449 |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-10-17 12:01 UTC, harishp8889 requested changes

2024-10-17 12:01 UTC, harishp8889 commented on tests/e2e/testfiles/minimal-testfiles/storage_csm_powermax.yaml
> +      image: "dellemc/csi-powermax:nightly"
Please use Quay images

2024-10-18 09:42 UTC, harishp8889 approved these changes
lgtm

2024-10-18 09:45 UTC, AkshaySainiDell approved these changes

2024-10-18 09:46 UTC, merged