updated powermax sample file and test files
dell/csm-operator pull request #776
Opened 2024-11-13 12:24 UTC by harishp8889

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-11-19 12:22 UTC, nitesh3108 requested changes
remove X_CSI_POWERMAX_ENDPOINT from operatorconfig as well

2024-11-19 16:00 UTC, harishp8889 commented
> remove X_CSI_POWERMAX_ENDPOINT from operatorconfig as well
 It is essential for the driver to start without that the driver will fail. One mandatory unisphere which is accessible must be present.

2024-11-19 16:23 UTC, ChristianAtDell commented
Merged `main` into this branch and addressed merge conflict, which should bring UT coverage up unless code was added and not tested in this branch.

2024-11-21 05:26 UTC, nitesh3108 approved these changes

2024-11-21 06:26 UTC, meggm approved these changes

2024-11-21 06:26 UTC, merged