Fix the e2e tests
dell/csm-operator pull request #829
Opened 2024-12-17 13:01 UTC by meggm

# Description
Fix the E2E tests with making changes to the **imagePullPolicy** for the nightly image as Always

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility
- [X] I have executed the relevant end-to-end test scenarios

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-12-18 13:37 UTC, harishp8889 approved these changes

2024-12-18 14:16 UTC, HarishH-DELL approved these changes

2024-12-18 14:40 UTC, gallacher requested changes
Please describe what is being fixed and why.  Where is the GitHub issue link?

2024-12-19 07:38 UTC, mgandharva commented
> Please describe what is being fixed and why. Where is the GitHub issue link?

Github issue updated, please review.

2024-12-20 12:22 UTC, gallacher approved these changes

2024-12-20 12:24 UTC, merged