Added csm delete validation steps in E2E
dell/csm-operator pull request #839
Opened 2024-12-27 09:53 UTC by mgandharva

# Description
Added E2E validation step to verify if the CSM got deleted after the deletion step.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility
- [ ] I have executed the relevant end-to-end test scenarios

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2025-01-01 06:45 UTC, ashleyvjoy submitted a review, later dismissed

2025-01-01 07:24 UTC, karthikk92 submitted a review, later dismissed

2025-01-01 09:17 UTC, riya-kaushal7997 submitted a review, later dismissed

2025-01-01 11:51 UTC, mgandharva commented on tests/e2e/testfiles/minimal-testfiles/scenarios.yaml
> +    - "Validate [powerstore] driver from CR [1] is installed"
resolved

2025-01-01 12:28 UTC, ashleyvjoy submitted a review, later dismissed

2025-01-02 08:27 UTC, harishp8889 requested changes

2025-01-02 09:41 UTC, mgandharva commented on tests/e2e/testfiles/storage_csm_powermax_sidecar.yaml
> +          image: quay.io/dell/container-storage-modules/csipowermax-reverseproxy:nightly
resolved, please review!

2025-01-02 09:42 UTC, harishp8889 approved these changes

2025-01-02 09:43 UTC, ashleyvjoy approved these changes

2025-01-02 09:43 UTC, merged