Add PowerScale v2.4.0 support
dell/csm-operator pull request #97
Opened 2022-08-22 21:30 UTC by jooseppi-luna

# Description
Adding PowerScale v2.4.0 support to csm-operator.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/350 |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Installed PowerScale 2.4.0 with new files, confirmed working. Used `dellemc/csi-isilon:nightly` since v2.4.0 is not released yet.

2022-08-23 06:24 UTC, jooseppi-luna commented
*Please note:* The image scanner failure is not due to the changes in this PR, as I also ran actions on a fresh branch that I cut off of main and made no changes to and got the same errors:

https://github.com/dell/csm-operator/actions/runs/2909282076

I will look into figuring out how to handle it, but in the meanwhile, please do review this PR anyway, since the failure is not due to the changes here.

2022-08-23 09:36 UTC, rensyct commented on operatorconfig/moduleconfig/common/version-values.yaml
> +      replication: "v1.4.0"
Should replication point to v1.3.0

2022-08-23 09:36 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
Update the sidecar version to v3.4.0

2022-08-23 09:36 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.4.0
Update the sidecar version to v5.0.1

2022-08-23 09:36 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
Update the sidecar version to v3.1.0

2022-08-23 09:36 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
Update the version to v5.0.1

2022-08-23 09:36 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/node.yaml
> +          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
Update the version to v2.5.1

2022-08-23 16:01 UTC, JacobGros approved these changes

2022-08-23 18:49 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
Please change this version to v1.4.0

2022-08-23 18:49 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.5.1
should be v0.5.0

2022-09-01 19:52 UTC, JacobGros approved these changes

2022-09-06 11:56 UTC, rensyct requested changes

2022-09-06 11:56 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
sidecar to be updated to v1.5.0

2022-09-06 11:56 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
sidecar needs to be updated v3.5.0

2022-09-06 11:56 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.5.0
sidecar needs to be updated to v0.6.0

2022-09-06 11:56 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
sidecar needs to be updated to v3.2.1

2022-09-06 11:56 UTC, rensyct commented on operatorconfig/driverconfig/powerscale/v2.4.0/controller.yaml
> +          image: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
sidecar needs to be updated to v6.0.1

2022-09-06 15:40 UTC, rensyct approved these changes

2022-09-06 15:46 UTC, JacobGros approved these changes

2022-09-06 16:19 UTC, merged